// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivity(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddActivity'](arg1, arg2, arg3, arg4);
}

export function AuthSignIn(arg1, arg2) {
  return window['go']['main']['App']['AuthSignIn'](arg1, arg2);
}

export function AuthSignOut() {
  return window['go']['main']['App']['AuthSignOut']();
}

export function AuthSignUp(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthSignUp'](arg1, arg2, arg3);
}

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function Export(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Export'](arg1, arg2, arg3, arg4);
}

export function GetRunning() {
  return window['go']['main']['App']['GetRunning']();
}

export function ListRecent(arg1) {
  return window['go']['main']['App']['ListRecent'](arg1);
}

export function ListToday() {
  return window['go']['main']['App']['ListToday']();
}

export function Projects() {
  return window['go']['main']['App']['Projects']();
}

export function RemoveActivity(arg1) {
  return window['go']['main']['App']['RemoveActivity'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['main']['App']['Start'](arg1, arg2);
}

export function StartAt(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAt'](arg1, arg2, arg3);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function SyncSetEnabled(arg1) {
  return window['go']['main']['App']['SyncSetEnabled'](arg1);
}

export function SyncStatus() {
  return window['go']['main']['App']['SyncStatus']();
}

export function TeamsConnect() {
  return window['go']['main']['App']['TeamsConnect']();
}

export function TeamsDisconnect() {
  return window['go']['main']['App']['TeamsDisconnect']();
}

export function TeamsGetStatus() {
  return window['go']['main']['App']['TeamsGetStatus']();
}

export function TeamsSetEnabled(arg1) {
  return window['go']['main']['App']['TeamsSetEnabled'](arg1);
}

export function TeamsSetTrackedProjects(arg1) {
  return window['go']['main']['App']['TeamsSetTrackedProjects'](arg1);
}

export function UpdateActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateActivity'](arg1, arg2, arg3, arg4, arg5);
}
