// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivity(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddActivity'](arg1, arg2, arg3, arg4);
}

export function AuthResendVerification(arg1) {
  return window['go']['main']['App']['AuthResendVerification'](arg1);
}

export function AuthSignIn(arg1, arg2) {
  return window['go']['main']['App']['AuthSignIn'](arg1, arg2);
}

export function AuthSignOut() {
  return window['go']['main']['App']['AuthSignOut']();
}

export function AuthSignUp(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthSignUp'](arg1, arg2, arg3);
}

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function AuthVerifyEmail(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthVerifyEmail'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function Export(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Export'](arg1, arg2, arg3, arg4);
}

export function GetRunning() {
  return window['go']['main']['App']['GetRunning']();
}

export function ListPastYear() {
  return window['go']['main']['App']['ListPastYear']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRecent(arg1) {
  return window['go']['main']['App']['ListRecent'](arg1);
}

export function ListToday() {
  return window['go']['main']['App']['ListToday']();
}

export function Projects() {
  return window['go']['main']['App']['Projects']();
}

export function RemoveActivity(arg1) {
  return window['go']['main']['App']['RemoveActivity'](arg1);
}

export function SharingAcceptInvite(arg1) {
  return window['go']['main']['App']['SharingAcceptInvite'](arg1);
}

export function SharingAddMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['SharingAddMember'](arg1, arg2, arg3);
}

export function SharingCreateLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['SharingCreateLink'](arg1, arg2, arg3);
}

export function SharingCreateTeam(arg1) {
  return window['go']['main']['App']['SharingCreateTeam'](arg1);
}

export function SharingDeclineInvite(arg1) {
  return window['go']['main']['App']['SharingDeclineInvite'](arg1);
}

export function SharingDeleteTeam(arg1) {
  return window['go']['main']['App']['SharingDeleteTeam'](arg1);
}

export function SharingInviteByEmail(arg1, arg2, arg3) {
  return window['go']['main']['App']['SharingInviteByEmail'](arg1, arg2, arg3);
}

export function SharingLeaveTeam(arg1) {
  return window['go']['main']['App']['SharingLeaveTeam'](arg1);
}

export function SharingListLinks() {
  return window['go']['main']['App']['SharingListLinks']();
}

export function SharingListTeams() {
  return window['go']['main']['App']['SharingListTeams']();
}

export function SharingRemoveMember(arg1, arg2) {
  return window['go']['main']['App']['SharingRemoveMember'](arg1, arg2);
}

export function SharingRenameTeam(arg1, arg2) {
  return window['go']['main']['App']['SharingRenameTeam'](arg1, arg2);
}

export function SharingRevokeLink(arg1) {
  return window['go']['main']['App']['SharingRevokeLink'](arg1);
}

export function SharingSetTeamShare(arg1, arg2, arg3) {
  return window['go']['main']['App']['SharingSetTeamShare'](arg1, arg2, arg3);
}

export function SharingSharedEntries() {
  return window['go']['main']['App']['SharingSharedEntries']();
}

export function SharingTeamMembers(arg1) {
  return window['go']['main']['App']['SharingTeamMembers'](arg1);
}

export function SharingTeamShare(arg1) {
  return window['go']['main']['App']['SharingTeamShare'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['main']['App']['Start'](arg1, arg2);
}

export function StartAt(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAt'](arg1, arg2, arg3);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function SyncSetEnabled(arg1) {
  return window['go']['main']['App']['SyncSetEnabled'](arg1);
}

export function SyncStatus() {
  return window['go']['main']['App']['SyncStatus']();
}

export function TeamsConnect() {
  return window['go']['main']['App']['TeamsConnect']();
}

export function TeamsDisconnect() {
  return window['go']['main']['App']['TeamsDisconnect']();
}

export function TeamsGetStatus() {
  return window['go']['main']['App']['TeamsGetStatus']();
}

export function TeamsSetEnabled(arg1) {
  return window['go']['main']['App']['TeamsSetEnabled'](arg1);
}

export function TeamsSetTrackedProjects(arg1) {
  return window['go']['main']['App']['TeamsSetTrackedProjects'](arg1);
}

export function UpdateActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateActivity'](arg1, arg2, arg3, arg4, arg5);
}
