// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRunning() {
  return window['go']['main']['App']['GetRunning']();
}

export function ListRecent(arg1) {
  return window['go']['main']['App']['ListRecent'](arg1);
}

export function ListToday() {
  return window['go']['main']['App']['ListToday']();
}

export function Projects() {
  return window['go']['main']['App']['Projects']();
}

export function RemoveActivity(arg1) {
  return window['go']['main']['App']['RemoveActivity'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['main']['App']['Start'](arg1, arg2);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function UpdateActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateActivity'](arg1, arg2, arg3, arg4, arg5);
}
