// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {neonauth} from '../models';
import {main} from '../models';
import {projects} from '../models';
import {neonsync} from '../models';
import {teams} from '../models';

export function ActivityLogPath():Promise<string>;

export function AddActivity(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Activity>;

export function AppVersion():Promise<string>;

export function ApplicationDataDirectory():Promise<string>;

export function AuthResendVerification(arg1:string):Promise<void>;

export function AuthSignIn(arg1:string,arg2:string):Promise<neonauth.Status>;

export function AuthSignOut():Promise<void>;

export function AuthSignUp(arg1:string,arg2:string,arg3:string):Promise<neonauth.Status>;

export function AuthStatus():Promise<neonauth.Status>;

export function AuthVerifyEmail(arg1:string,arg2:string,arg3:string):Promise<neonauth.Status>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CreateProject(arg1:string):Promise<projects.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function Export(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function GetRunning():Promise<models.Activity>;

export function ListPastYear():Promise<Array<models.Activity>>;

export function ListProjects():Promise<Array<projects.Project>>;

export function ListRecent(arg1:number):Promise<Array<models.Activity>>;

export function ListToday():Promise<Array<models.Activity>>;

export function OpenActivityLog():Promise<void>;

export function OpenApplicationDataDirectory():Promise<void>;

export function Projects():Promise<Array<string>>;

export function RemoveActivity(arg1:models.Activity):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<projects.Project>;

export function SetProjectColor(arg1:string,arg2:string):Promise<projects.Project>;

export function SharingAcceptInvite(arg1:string):Promise<void>;

export function SharingAddMember(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SharingCreateLink(arg1:Array<string>,arg2:number,arg3:number):Promise<neonsync.LinkShare>;

export function SharingCreateTeam(arg1:string):Promise<main.TeamView>;

export function SharingDeclineInvite(arg1:string):Promise<void>;

export function SharingDeleteTeam(arg1:string):Promise<void>;

export function SharingInviteByEmail(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SharingLeaveTeam(arg1:string):Promise<void>;

export function SharingListLinks():Promise<Array<neonsync.LinkShareInfo>>;

export function SharingListTeams():Promise<Array<main.TeamView>>;

export function SharingProjectShares():Promise<Array<neonsync.ProjectShare>>;

export function SharingRemoveMember(arg1:string,arg2:string):Promise<void>;

export function SharingRenameTeam(arg1:string,arg2:string):Promise<void>;

export function SharingRevokeLink(arg1:string):Promise<void>;

export function SharingSetTeamShare(arg1:string,arg2:Array<string>,arg3:number):Promise<void>;

export function SharingSharedEntries():Promise<Array<main.SharedActivity>>;

export function SharingTeamMembers(arg1:string):Promise<Array<neonsync.TeamMember>>;

export function SharingTeamShare(arg1:string):Promise<neonsync.ShareView>;

export function Start(arg1:string,arg2:string):Promise<models.Activity>;

export function StartAt(arg1:string,arg2:string,arg3:string):Promise<models.Activity>;

export function Stop():Promise<models.Activity>;

export function SyncNow():Promise<neonsync.SyncStatus>;

export function SyncSetEnabled(arg1:boolean):Promise<neonsync.SyncStatus>;

export function SyncStatus():Promise<neonsync.SyncStatus>;

export function TeamsConnect():Promise<void>;

export function TeamsDisconnect():Promise<void>;

export function TeamsGetStatus():Promise<teams.Status>;

export function TeamsSetEnabled(arg1:boolean):Promise<void>;

export function TeamsSetTrackedProjects(arg1:Array<string>):Promise<void>;

export function UpdateActivity(arg1:models.Activity,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Activity>;
