// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetRunning():Promise<models.Activity>;

export function ListRecent(arg1:number):Promise<Array<models.Activity>>;

export function ListToday():Promise<Array<models.Activity>>;

export function Projects():Promise<Array<string>>;

export function RemoveActivity(arg1:models.Activity):Promise<void>;

export function Start(arg1:string,arg2:string):Promise<models.Activity>;

export function Stop():Promise<models.Activity>;

export function UpdateActivity(arg1:models.Activity,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Activity>;
