// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotesRepository creates a new instance of MockNotesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotesRepository {
	mock := &MockNotesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotesRepository is an autogenerated mock type for the NotesRepository type
type MockNotesRepository struct {
	mock.Mock
}

type MockNotesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotesRepository) EXPECT() *MockNotesRepository_Expecter {
	return &MockNotesRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockNotesRepository
func (_mock *MockNotesRepository) Get(ctx context.Context, activityID string, date time.Time) (string, []string, error) {
	ret := _mock.Called(ctx, activityID, date)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (string, []string, error)); ok {
		return returnFunc(ctx, activityID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) string); ok {
		r0 = returnFunc(ctx, activityID, date)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) []string); ok {
		r1 = returnFunc(ctx, activityID, date)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, time.Time) error); ok {
		r2 = returnFunc(ctx, activityID, date)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotesRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNotesRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
//   - date time.Time
func (_e *MockNotesRepository_Expecter) Get(ctx interface{}, activityID interface{}, date interface{}) *MockNotesRepository_Get_Call {
	return &MockNotesRepository_Get_Call{Call: _e.mock.On("Get", ctx, activityID, date)}
}

func (_c *MockNotesRepository_Get_Call) Run(run func(ctx context.Context, activityID string, date time.Time)) *MockNotesRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotesRepository_Get_Call) Return(s string, strings []string, err error) *MockNotesRepository_Get_Call {
	_c.Call.Return(s, strings, err)
	return _c
}

func (_c *MockNotesRepository_Get_Call) RunAndReturn(run func(ctx context.Context, activityID string, date time.Time) (string, []string, error)) *MockNotesRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockNotesRepository
func (_mock *MockNotesRepository) Save(ctx context.Context, activityID string, date time.Time, notes string, tags []string) error {
	ret := _mock.Called(ctx, activityID, date, notes, tags)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, string, []string) error); ok {
		r0 = returnFunc(ctx, activityID, date, notes, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotesRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockNotesRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - activityID string
//   - date time.Time
//   - notes string
//   - tags []string
func (_e *MockNotesRepository_Expecter) Save(ctx interface{}, activityID interface{}, date interface{}, notes interface{}, tags interface{}) *MockNotesRepository_Save_Call {
	return &MockNotesRepository_Save_Call{Call: _e.mock.On("Save", ctx, activityID, date, notes, tags)}
}

func (_c *MockNotesRepository_Save_Call) Run(run func(ctx context.Context, activityID string, date time.Time, notes string, tags []string)) *MockNotesRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockNotesRepository_Save_Call) Return(err error) *MockNotesRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotesRepository_Save_Call) RunAndReturn(run func(ctx context.Context, activityID string, date time.Time, notes string, tags []string) error) *MockNotesRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
