// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/kriuchkov/tock/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityResolver creates a new instance of MockActivityResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityResolver {
	mock := &MockActivityResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityResolver is an autogenerated mock type for the ActivityResolver type
type MockActivityResolver struct {
	mock.Mock
}

type MockActivityResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityResolver) EXPECT() *MockActivityResolver_Expecter {
	return &MockActivityResolver_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockActivityResolver
func (_mock *MockActivityResolver) Add(ctx context.Context, req models.AddActivityRequest) (*models.Activity, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AddActivityRequest) (*models.Activity, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AddActivityRequest) *models.Activity); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.AddActivityRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityResolver_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockActivityResolver_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.AddActivityRequest
func (_e *MockActivityResolver_Expecter) Add(ctx interface{}, req interface{}) *MockActivityResolver_Add_Call {
	return &MockActivityResolver_Add_Call{Call: _e.mock.On("Add", ctx, req)}
}

func (_c *MockActivityResolver_Add_Call) Run(run func(ctx context.Context, req models.AddActivityRequest)) *MockActivityResolver_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.AddActivityRequest
		if args[1] != nil {
			arg1 = args[1].(models.AddActivityRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityResolver_Add_Call) Return(activity *models.Activity, err error) *MockActivityResolver_Add_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityResolver_Add_Call) RunAndReturn(run func(ctx context.Context, req models.AddActivityRequest) (*models.Activity, error)) *MockActivityResolver_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecent provides a mock function for the type MockActivityResolver
func (_mock *MockActivityResolver) GetRecent(ctx context.Context, limit int) ([]models.Activity, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.Activity, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.Activity); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityResolver_GetRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecent'
type MockActivityResolver_GetRecent_Call struct {
	*mock.Call
}

// GetRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockActivityResolver_Expecter) GetRecent(ctx interface{}, limit interface{}) *MockActivityResolver_GetRecent_Call {
	return &MockActivityResolver_GetRecent_Call{Call: _e.mock.On("GetRecent", ctx, limit)}
}

func (_c *MockActivityResolver_GetRecent_Call) Run(run func(ctx context.Context, limit int)) *MockActivityResolver_GetRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityResolver_GetRecent_Call) Return(activitys []models.Activity, err error) *MockActivityResolver_GetRecent_Call {
	_c.Call.Return(activitys, err)
	return _c
}

func (_c *MockActivityResolver_GetRecent_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]models.Activity, error)) *MockActivityResolver_GetRecent_Call {
	_c.Call.Return(run)
	return _c
}

// GetReport provides a mock function for the type MockActivityResolver
func (_mock *MockActivityResolver) GetReport(ctx context.Context, filter models.ActivityFilter) (*models.Report, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetReport")
	}

	var r0 *models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ActivityFilter) (*models.Report, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ActivityFilter) *models.Report); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ActivityFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityResolver_GetReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReport'
type MockActivityResolver_GetReport_Call struct {
	*mock.Call
}

// GetReport is a helper method to define mock.On call
//   - ctx context.Context
//   - filter models.ActivityFilter
func (_e *MockActivityResolver_Expecter) GetReport(ctx interface{}, filter interface{}) *MockActivityResolver_GetReport_Call {
	return &MockActivityResolver_GetReport_Call{Call: _e.mock.On("GetReport", ctx, filter)}
}

func (_c *MockActivityResolver_GetReport_Call) Run(run func(ctx context.Context, filter models.ActivityFilter)) *MockActivityResolver_GetReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(models.ActivityFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityResolver_GetReport_Call) Return(report *models.Report, err error) *MockActivityResolver_GetReport_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockActivityResolver_GetReport_Call) RunAndReturn(run func(ctx context.Context, filter models.ActivityFilter) (*models.Report, error)) *MockActivityResolver_GetReport_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockActivityResolver
func (_mock *MockActivityResolver) List(ctx context.Context, filter models.ActivityFilter) ([]models.Activity, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ActivityFilter) ([]models.Activity, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ActivityFilter) []models.Activity); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ActivityFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityResolver_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockActivityResolver_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter models.ActivityFilter
func (_e *MockActivityResolver_Expecter) List(ctx interface{}, filter interface{}) *MockActivityResolver_List_Call {
	return &MockActivityResolver_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockActivityResolver_List_Call) Run(run func(ctx context.Context, filter models.ActivityFilter)) *MockActivityResolver_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(models.ActivityFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityResolver_List_Call) Return(activitys []models.Activity, err error) *MockActivityResolver_List_Call {
	_c.Call.Return(activitys, err)
	return _c
}

func (_c *MockActivityResolver_List_Call) RunAndReturn(run func(ctx context.Context, filter models.ActivityFilter) ([]models.Activity, error)) *MockActivityResolver_List_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockActivityResolver
func (_mock *MockActivityResolver) Start(ctx context.Context, req models.StartActivityRequest) (*models.Activity, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StartActivityRequest) (*models.Activity, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StartActivityRequest) *models.Activity); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.StartActivityRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityResolver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockActivityResolver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.StartActivityRequest
func (_e *MockActivityResolver_Expecter) Start(ctx interface{}, req interface{}) *MockActivityResolver_Start_Call {
	return &MockActivityResolver_Start_Call{Call: _e.mock.On("Start", ctx, req)}
}

func (_c *MockActivityResolver_Start_Call) Run(run func(ctx context.Context, req models.StartActivityRequest)) *MockActivityResolver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StartActivityRequest
		if args[1] != nil {
			arg1 = args[1].(models.StartActivityRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityResolver_Start_Call) Return(activity *models.Activity, err error) *MockActivityResolver_Start_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityResolver_Start_Call) RunAndReturn(run func(ctx context.Context, req models.StartActivityRequest) (*models.Activity, error)) *MockActivityResolver_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockActivityResolver
func (_mock *MockActivityResolver) Stop(ctx context.Context, req models.StopActivityRequest) (*models.Activity, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 *models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StopActivityRequest) (*models.Activity, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StopActivityRequest) *models.Activity); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.StopActivityRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityResolver_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockActivityResolver_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.StopActivityRequest
func (_e *MockActivityResolver_Expecter) Stop(ctx interface{}, req interface{}) *MockActivityResolver_Stop_Call {
	return &MockActivityResolver_Stop_Call{Call: _e.mock.On("Stop", ctx, req)}
}

func (_c *MockActivityResolver_Stop_Call) Run(run func(ctx context.Context, req models.StopActivityRequest)) *MockActivityResolver_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StopActivityRequest
		if args[1] != nil {
			arg1 = args[1].(models.StopActivityRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityResolver_Stop_Call) Return(activity *models.Activity, err error) *MockActivityResolver_Stop_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityResolver_Stop_Call) RunAndReturn(run func(ctx context.Context, req models.StopActivityRequest) (*models.Activity, error)) *MockActivityResolver_Stop_Call {
	_c.Call.Return(run)
	return _c
}
