// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/kriuchkov/tock/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityRepository creates a new instance of MockActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityRepository {
	mock := &MockActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityRepository is an autogenerated mock type for the ActivityRepository type
type MockActivityRepository struct {
	mock.Mock
}

type MockActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityRepository) EXPECT() *MockActivityRepository_Expecter {
	return &MockActivityRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) Find(ctx context.Context, filter models.ActivityFilter) ([]models.Activity, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ActivityFilter) ([]models.Activity, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ActivityFilter) []models.Activity); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ActivityFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockActivityRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter models.ActivityFilter
func (_e *MockActivityRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockActivityRepository_Find_Call {
	return &MockActivityRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockActivityRepository_Find_Call) Run(run func(ctx context.Context, filter models.ActivityFilter)) *MockActivityRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ActivityFilter
		if args[1] != nil {
			arg1 = args[1].(models.ActivityFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_Find_Call) Return(activitys []models.Activity, err error) *MockActivityRepository_Find_Call {
	_c.Call.Return(activitys, err)
	return _c
}

func (_c *MockActivityRepository_Find_Call) RunAndReturn(run func(ctx context.Context, filter models.ActivityFilter) ([]models.Activity, error)) *MockActivityRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindLast provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) FindLast(ctx context.Context) (*models.Activity, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindLast")
	}

	var r0 *models.Activity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.Activity, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.Activity); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Activity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityRepository_FindLast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLast'
type MockActivityRepository_FindLast_Call struct {
	*mock.Call
}

// FindLast is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockActivityRepository_Expecter) FindLast(ctx interface{}) *MockActivityRepository_FindLast_Call {
	return &MockActivityRepository_FindLast_Call{Call: _e.mock.On("FindLast", ctx)}
}

func (_c *MockActivityRepository_FindLast_Call) Run(run func(ctx context.Context)) *MockActivityRepository_FindLast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActivityRepository_FindLast_Call) Return(activity *models.Activity, err error) *MockActivityRepository_FindLast_Call {
	_c.Call.Return(activity, err)
	return _c
}

func (_c *MockActivityRepository_FindLast_Call) RunAndReturn(run func(ctx context.Context) (*models.Activity, error)) *MockActivityRepository_FindLast_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) Save(ctx context.Context, activity models.Activity) error {
	ret := _mock.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Activity) error); ok {
		r0 = returnFunc(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockActivityRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - activity models.Activity
func (_e *MockActivityRepository_Expecter) Save(ctx interface{}, activity interface{}) *MockActivityRepository_Save_Call {
	return &MockActivityRepository_Save_Call{Call: _e.mock.On("Save", ctx, activity)}
}

func (_c *MockActivityRepository_Save_Call) Run(run func(ctx context.Context, activity models.Activity)) *MockActivityRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Activity
		if args[1] != nil {
			arg1 = args[1].(models.Activity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_Save_Call) Return(err error) *MockActivityRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityRepository_Save_Call) RunAndReturn(run func(ctx context.Context, activity models.Activity) error) *MockActivityRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockActivityRepository
func (_mock *MockActivityRepository) Remove(ctx context.Context, activity models.Activity) error {
	ret := _mock.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Activity) error); ok {
		r0 = returnFunc(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockActivityRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - activity models.Activity
func (_e *MockActivityRepository_Expecter) Remove(ctx interface{}, activity interface{}) *MockActivityRepository_Remove_Call {
	return &MockActivityRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, activity)}
}

func (_c *MockActivityRepository_Remove_Call) Run(run func(ctx context.Context, activity models.Activity)) *MockActivityRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Activity
		if args[1] != nil {
			arg1 = args[1].(models.Activity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityRepository_Remove_Call) Return(err error) *MockActivityRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, activity models.Activity) error) *MockActivityRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
